substitutions:
  _GO_VERSION: 1.13.5
  _GCLOUD_CONTAINER_HOST: gcr.io
  _IMAGE_NAME: chatstatz-webhooks

timeout: 120s

images:
  - "${_GCLOUD_CONTAINER_HOST}/$PROJECT_ID/${_IMAGE_NAME}"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--build-arg", "GO_VERSION=${_GO_VERSION}", "-t", "${_GCLOUD_CONTAINER_HOST}/$PROJECT_ID/${_IMAGE_NAME}", "."]
